### ISSUE TITLE
Doesn't work on mobile

### ISSUE THREAD

**Issue by nazarposhta** [leoasis/react-sound#15]
Hello! I'm using this package and noted then it not works on mobile phone (android) and on iPad. Quite strange - because my  code is very simple and works on the desktop.
Any idea?

**Comment by DvirSh** [comment]
Probably too late, but there is an [issue with soundmanager2](https://github.com/scottschiller/SoundManager2/issues/101)
It is currently in PR there, so we need to keep our hopes high 🤞

**Comment by leoasis** [comment]
Hi! Awesome, I'm down for making it work on mobile. I currently don't have that use case, but if you are willing to test it and send a PR, I'll definitely merge it!

**Comment by DvirSh** [comment]
The problem is that soundmanager2 won't accept the pull request to allow that, and if we want it fixed we need to pull from the PR branch... :(

**Comment by leoasis** [comment]
This should have been addressed by #24, if not, feel free to reopen!

**Comment by sanraw54321** [comment]
Hi I am using this package , and seeing the same issue , where my app runs in desktop but its not working in my tab or mobile.
As mentioned by you , I am setting up  as below:
componentDidMount() {
    console.log(soundManager);
    soundManager.setup({ ignoreMobileRestrictions : true
    });
  }

but its still not working.

Basic sample code base below , the way I am using. This works in my laptop , but not in my tab.
------------------------------
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import Sound from 'react-sound';

class MyComponentWithSound extends React.Component {

  componentDidMount() {
    console.log(soundManager);
    soundManager.setup({
      ignoreMobileRestrictions: true
    });
  }
  render() {
    return <Sound url="http://www.studiowan.com/ICAN/BRUITAGES/Animals/Alligator%20Hiss%2001.wav"
      playStatus={Sound.status.PLAYING} />
  }
}

class App extends Component {
  constructor(props) {
    super(props);
  }



  // Normally you would want to split things out into separate components.
  // But in this example everything is just done in one place for simplicity
  render() {
    return (
      <MyComponentWithSound />
    );
  }
}

// Put the thing into the DOM!
ReactDOM.render(<App />, document.getElementById('app'));

**Comment by nazarposhta** [comment]
@sanraw54321 As remember I just left that and implemented my app based on HTML 5 AUDIO API by myself.
